### ISSUE TITLE
`colMeans` returns sums when used with `aggregate.matrix`

### ISSUE THREAD

**Issue by ekernf01** [cran/Matrix.utils#1]
It seems like `Matrix.utils::aggregate.Matrix` does not work correctly with `colMeans`. Try this:

    x = matrix( 1:10, ncol = 2 )
    x = as( x, "sparseMatrix" )
    colMeans( x )
    Matrix.utils::aggregate.Matrix( x = x, 
                                    groupings = factor( rep("A", 5) ), 
                                    fun = "colMeans" )
    Matrix.utils::aggregate.Matrix( x = x, 
                                    groupings = factor( rep("A", 5) ), 
                                    fun = "colSums" )

**Comment by ekernf01** [comment]
Update: it seems that this issue runs much deeper, and `aggregate.Matrix` only works for a couple of functions (`count`, `mean`). For other functions, `aggregate.Matrix` silently does the wrong thing. It would be helpful if this behavior were documented.

**Comment by cvarrichio** [comment]
Thanks for pointing this out.  Yes, this is poorly documented.  `aggregate.Matrix` only works for `count, sum, and mean`, which are passed as strings to the parameter `fun`.  I will improve the documentation in the next release, and perhaps this will be expanded in the future.

**Comment by cvarrichio** [comment]
The documentation has been improved in version 0.9.4, just released.

**Comment by ekernf01** [comment]
Thank you!
